# Generated by Django 5.2.17 on 2026-08-31 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_publication_entry_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус автора',
                'verbose_name_plural': 'Статусы авторов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CitationDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'База данных цитирования',
                'verbose_name_plural': 'Базы данных цитирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код кафедры')),
                ('full_name', models.TextField(verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет для отображения')),
            ],
            options={
                'verbose_name': 'Статус записи',
                'verbose_name_plural': 'Статусы записей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет для отображения')),
            ],
            options={
                'verbose_name': 'Статус модерации',
                'verbose_name_plural': 'Статусы модерации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер месяца')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=10, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PublicationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код уровня')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уровень публикации',
                'verbose_name_plural': 'Уровни публикаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип публикации',
                'verbose_name_plural': 'Типы публикаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код периода')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отчётный период',
                'verbose_name_plural': 'Отчётные периоды',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название результата')),
                ('display_name', models.CharField(max_length=50, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип результата',
                'verbose_name_plural': 'Типы результатов',
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='publication',
            name='core_public_publica_101f9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='publication',
            name='core_public_citatio_c7c1a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='publication',
            name='core_public_reporti_9131bf_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='core_public_status__927a4c_idx',
            old_name='core_public_status_bb8ee0_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='core_public_departm_bbe01a_idx',
            old_name='core_public_departm_398151_idx',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='moderation_status',
        ),
        migrations.AlterField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_publications', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.authorstatus', verbose_name='Статус автора'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.citationdatabase', verbose_name='База данных и система цитирования'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='publications_by_status', to='core.entrystatus', verbose_name='Статус записи'),
        ),
        migrations.AddField(
            model_name='publication',
            name='moderation_status_rel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='publications_by_moderation_status', to='core.moderationstatus', verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='entry_month',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.month', verbose_name='Месяц внесения'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.publicationscope', verbose_name='Уровень публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.publicationtype', verbose_name='Тип публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reporting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.reportingperiod', verbose_name='Отчётный период'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.resulttype', verbose_name='Результат'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type', '-created_at'], name='core_public_publica_2c6b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['citation_db', '-created_at'], name='core_public_citatio_406e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['reporting_period', '-created_at'], name='core_public_reporti_cb3611_idx'),
        ),
    ]
