# Generated by Django 6.0.3 on 2026-08-31 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_publication_entry_month'),
        ('users', '0003_add_nio_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorStatusDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус автора',
                'verbose_name_plural': 'Статусы авторов',
            },
        ),
        migrations.CreateModel(
            name='CitationDatabaseDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'База цитирования',
                'verbose_name_plural': 'Базы цитирования',
            },
        ),
        migrations.CreateModel(
            name='PublicationScopeDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Уровень публикации',
                'verbose_name_plural': 'Уровни публикаций',
            },
        ),
        migrations.CreateModel(
            name='PublicationTypeDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Тип публикации',
                'verbose_name_plural': 'Типы публикаций',
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriodDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Отчётный период',
                'verbose_name_plural': 'Отчётные периоды',
            },
        ),
        migrations.CreateModel(
            name='ResultDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='core_public_departm_bbe01a_idx',
            old_name='core_public_departm_398151_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='core_public_publica_558f10_idx',
            old_name='core_public_publica_101f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='core_public_citatio_d7c2d6_idx',
            old_name='core_public_citatio_c7c1a7_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='core_public_reporti_f686e4_idx',
            old_name='core_public_reporti_9131bf_idx',
        ),
        migrations.AlterField(
            model_name='publication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='users.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.authorstatusdict', verbose_name='Статус автора'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.citationdatabasedict', verbose_name='База данных и система цитирования'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.publicationscopedict', verbose_name='Уровень публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.publicationtypedict', verbose_name='Тип публикации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reporting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.reportingperioddict', verbose_name='Отчётный период'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.resultdict', verbose_name='Результат'),
        ),
    ]
