# Generated by Django 5.2.17 on 2026-08-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_authorstatus_citationdatabase_department_entrystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttype',
            name='code',
            field=models.CharField(default='participant', max_length=50, unique=True, verbose_name='Код результата'),
        ),
    ]
